plugins:
  - plugins/customRules.js
rules:
  info-license-url:
    severity: error
  no-ambiguous-paths:
    severity: error
  no-invalid-media-type-examples:
    severity: error
  no-server-example.com:
    severity: error
  no-unused-components:
    severity: error
  operation-2xx-response:
    severity: error
  operation-operationId:
    severity: error
  no-enum-type-mismatch:
    severity: error
  no-example-value-and-externalValue:
    severity: error
  no-identical-paths:
    severity: error
  no-path-trailing-slash:
    severity: error
  no-server-trailing-slash:
    severity: error
  no-server-variables-empty-enum:
    severity: error
  no-undefined-server-variable:
    severity: error
  no-unresolved-refs:
    severity: error
  operation-operationId-unique:
    severity: error
  operation-operationId-url-safe:
    severity: error
  operation-parameters-unique:
    severity: error
  operation-summary:
    severity: error
  path-declaration-must-exist:
    severity: error
  path-not-include-query:
    severity: error
  path-parameters-defined:
    severity: error
  spec-components-invalid-map-name:
    severity: error
  spec:
    severity: error
  pinata/noAnonymousEnum:
    severity: error

  # Disable rules
  operation-4xx-response:
    severity: off
  tag-description:
    severity: off
  no-empty-servers:
    severity: off
  info-license:
    severity: off
  security-defined:
    severity: off
